### ISSUE TITLE
[Suggestion] Remove the "Chat messages can't be verified" message

### ISSUE THREAD

**Issue by Soapy7261** [Bendimester23/tihr#1]
I don't care, i don't need to know, who gives a crap? Its just annoying to see this little popup on my screen every time i load into a server that doesn't enforce secure profiles
![Screenshot 2023-02-23 165315](https://user-images.githubusercontent.com/81933267/221039018-3973bd29-a2dc-4795-b995-e94173189b9c.png)
Also, it should be toggleable with like mod menu or something to be able to enable/disable certain messages

**Comment by Bendimester23** [comment]
good idea, I'll make sure to include this in the next version

**Comment by Bendimester23** [comment]
The new version will be available as soon as modrinth and curseforge reviews it. However the config screen is not yet done as I was lazy.

**Comment by Bendimester23** [comment]
Turns out Modrinth doesn't review new versions so it's already available there.
