### ISSUE TITLE
New feature suggestions

### ISSUE THREAD

**Issue by ghost** [Bendimester23/tihr#2]
Set GUI scale to 2 by default
Set FOV to quake pro by default
Disable outdated resource pack warning

Other than that you count integrate these mods:
https://www.curseforge.com/minecraft/mc-mods/no-telemetry
https://www.curseforge.com/minecraft/mc-mods/no-chat-reports
(both fully open source)

Great mod though, I like what you're trying to accomplish

**Comment by Bendimester23** [comment]
Firstly, sorry for replaying late.
GUI scale 2 is a must, and while I too use FOV quake pro, I don't think it's as universal as GUI scale 2.
The outdated resource pack warning is a great idea, I'll certainly make it. Also those mods you've linked are also good ideas.

**Comment by Bendimester23** [comment]
With the exception of No Chat Reports and FOV quake pro, things you suggested are available on Modrinth and soon Curseforge

**Comment by ghost** [comment]
Hey there, no worries on the respond time I'm glad you added the features :)
Is there a specific reason you are using 1.19.3 for the mod version? Most people use the x.2 or x.5 versions so 1.19.2 would probably get you more downloads and be more convenient especially since a lot of mods are only up to 1.19.2

**Comment by ghost** [comment]
Also my only other suggestion besides the no chat reports would be to disable the narrator hotkey
If you are interested in that there is an open source mod for it https://github.com/545u/NoNarrator

As for the FOV not being universal, from my experience everyone I know always sets it to Quake Pro on fresh install, though I can also get your point. But then again some of my friends keep the Music on 20-30 and your mod disables it so neither are really universal.

The last thing that I think would be cool is uncapping FPS and turning on the FPS counter. Probably a more useful feature than the music, in my opinion.

**Comment by Bendimester23** [comment]
> Is there a specific reason you are using 1.19.3 for the mod version?

It was the latest when I made the project, but I plan on supporting more versions. I like the idea of disabling the narrator hotkey, but I don't know what do you mean by uncapping FPS(it it unlimited by default iirc) and the FPS counter(i only know of the F3 menu)

**Comment by ghost** [comment]
Actually by default its on Vsync, and I'm not sure if the fps counter is a Sodium/Optifine exclusive but its not really a big deal if it is, though to clarify I was refering to the little FPS counter at the top left you can enable in options.

Good luck on the project, if you do decide to downgrade to 1.19.2 you'd do me a huge favor as this mod would replace like 4 other small mods and I'd definitely put it into all of my modpacks, no pressure though.

**Comment by Bendimester23** [comment]
I think the FPS counter is an Optifine/Sodium Extras thing, however I might add it. Also I'll definitely downgrade to 1.19.2 at some point.

**Comment by Bendimester23** [comment]
The 1.19.2 version is up on Modrinth and (when done processing) on Curseforge.
