### ISSUE TITLE
Error doest allow game to launch

### ISSUE THREAD

**Issue by xGavi** [Bendimester23/tihr#3]
When trying to launch the game I get the following error:

> The game crashed whilst initializing game
> Error: java.lang.RuntimeException: Mixin transformation of com.mojang.text2speech.Narrator failed

[crash-2023-05-04_00.10.13-client.txt](https://github.com/Bendimester23/tihr/files/11392638/crash-2023-05-04_00.10.13-client.txt)

**Comment by Bendimester23** [comment]
I'll fix it tomorrow.
