### ISSUE TITLE
respecting config instead of reset every launch

### ISSUE THREAD

**Issue by DadoIrie** [Bendimester23/tihr#6]
Highly useful this mod, especially the recipe book logic removal with bigger modpacks - haven't found any mod which does this as most (if not all of them) do just remove the button.
now my biggest issue and real nuance here is the gui scale - could you make it if it's not set to auto (which is basically `guiScale:0` in the options.txt) the mod does not change it?
My preferred gui scale is 3 while maybe others might be 4 and this mod resets it every launch to 2 
would love to see that changed/fixed

edit: 1.19.2 btw (just in case) XD

**Comment by Bendimester23** [comment]
A new build should be available soon.

**Comment by Bendimester23** [comment]
It's up on Modrinth and Curseforge says its processing.

**Comment by Bendimester23** [comment]
Now its under review

**Comment by DadoIrie** [comment]
thanks a lot - sadly I switched to 1.20.1 ... will need to wait till THIR is updated for that version
